In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
import pandas as pd
df=pd.read_csv(r"/content/sample_data/cars_price.csv")

In [ ]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       205 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               205 non-null    object
 19  stroke             205 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    object
 22  peak-rpm           205 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [ ]:
df.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')

In [ ]:
df.describe()

,symboling,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

In [ ]:
df.nunique()

symboling              6
normalized-losses     52
make                  22
fuel-type              2
aspiration             2
num-of-doors           3
body-style             5
drive-wheels           3
engine-location        2
wheel-base            53
length                75
width                 44
height                49
curb-weight          171
engine-type            7
num-of-cylinders       7
engine-size           44
fuel-system            8
bore                  39
stroke                37
compression-ratio     32
horsepower            60
peak-rpm              24
city-mpg              29
highway-mpg           30
price                187
dtype: int64

In [ ]:
df.shape

(205, 26)

In [ ]:
df.iloc[:,-1].value_counts()

?        4
8921     2
18150    2
8845     2
8495     2
        ..
45400    1
16503    1
5389     1
6189     1
22625    1
Name: price, Length: 187, dtype: int64

In [ ]:
for i in df.columns:
    print(f'{i},{df[i].value_counts()}')

symboling, 0    67
 1    54
 2    32
 3    27
-1    22
-2     3
Name: symboling, dtype: int64
normalized-losses,?      41
161    11
91      8
150     7
134     6
128     6
104     6
85      5
94      5
65      5
102     5
74      5
168     5
103     5
95      5
106     4
93      4
118     4
148     4
122     4
83      3
125     3
154     3
115     3
137     3
101     3
119     2
87      2
89      2
192     2
197     2
158     2
81      2
188     2
194     2
153     2
129     2
108     2
110     2
164     2
145     2
113     2
256     1
107     1
90      1
231     1
142     1
121     1
78      1
98      1
186     1
77      1
Name: normalized-losses, dtype: int64
make,toyota           32
nissan           18
mazda            17
mitsubishi       13
honda            13
volkswagen       12
subaru           12
peugot           11
volvo            11
dodge             9
mercedes-benz     8
bmw               8
audi              7
plymouth          7
saab              6
porsche           5
isuzu             4
jaguar            3
chevrolet         3
alfa-romero       3
renault           2
mercury           1
Name: make, dtype: int64
fuel-type,gas       185
diesel     20
Name: fuel-type, dtype: int64
aspiration,std      168
turbo     37
Name: aspiration, dtype: int64
num-of-doors,four    114
two      89
?         2
Name: num-of-doors, dtype: int64
body-style,sedan          96
hatchback      70
wagon          25
hardtop         8
convertible     6
Name: body-style, dtype: int64
drive-wheels,fwd    120
rwd     76
4wd      9
Name: drive-wheels, dtype: int64
engine-location,front    202
rear       3
Name: engine-location, dtype: int64
wheel-base,94.5     21
93.7     20
95.7     13
96.5      8
97.3      7
98.4      7
104.3     6
100.4     6
107.9     6
98.8      6
99.1      6
96.3      6
109.1     5
93.1      5
97.2      5
95.9      5
102.4     5
97.0      4
95.3      4
114.2     4
101.2     4
110.0     3
103.5     3
89.5      3
105.8     3
96.1      2
102.9     2
104.5     2
91.3      2
96.9      2
88.6      2
113.0     2
99.8      2
115.6     2
103.3     2
86.6      2
104.9     2
93.3      1
99.4      1
99.5      1
88.4      1
94.3      1
96.0      1
95.1      1
93.0      1
102.0     1
106.7     1
108.0     1
96.6      1
99.2      1
112.0     1
102.7     1
120.9     1
Name: wheel-base, dtype: int64
length,157.3    15
188.8    11
171.7     7
186.7     7
166.3     7
         ..
165.6     1
187.5     1
180.3     1
208.1     1
199.2     1
Name: length, Length: 75, dtype: int64
width,63.8    24
66.5    23
65.4    15
63.6    11
64.4    10
68.4    10
64.0     9
65.5     8
65.2     7
64.2     6
66.3     6
65.6     6
67.2     6
67.9     5
66.9     5
65.7     4
68.9     4
64.8     4
63.9     3
70.3     3
71.7     3
71.4     3
65.0     3
68.3     2
67.7     2
64.1     2
66.1     2
69.6     2
64.6     2
72.0     1
68.0     1
70.5     1
61.8     1
66.0     1
62.5     1
70.6     1
72.3     1
66.6     1
63.4     1
60.3     1
70.9     1
66.4     1
66.2     1
68.8     1
Name: width, dtype: int64
height,50.8    14
52.0    12
55.7    12
54.1    10
54.5    10
55.5     9
56.7     8
54.3     8
52.6     7
56.1     7
51.6     7
53.0     6
52.8     6
54.9     6
50.2     6
53.7     5
55.1     5
50.6     5
49.6     4
58.7     4
53.3     4
52.5     3
59.1     3
56.2     3
49.7     3
57.5     3
53.5     3
54.4     2
53.9     2
56.3     2
50.5     2
59.8     2
56.5     2
54.7     2
48.8     2
49.4     2
51.4     2
51.0     1
54.8     1
55.4     1
56.0     1
55.2     1
53.2     1
47.8     1
55.9     1
52.4     1
55.6     1
53.1     1
58.3     1
Name: height, dtype: int64
curb-weight,2385    4
1918    3
2275    3
1989    3
2410    2
       ..
2370    1
2328    1
2833    1
2921    1
3062    1
Name: curb-weight, Length: 171, dtype: int64
engine-type,ohc      148
ohcf      15
ohcv      13
dohc      12
l         12
rotor      4
dohcv      1
Name: engine-type, dtype: int64
num-of-cylinders,four      159
six        24
five       11
eight       5
two         4
three       1
twelve      1
Name: num-of-cylinders, dtype: int64
engine-size,122    15
92     15
97     14
98     14
108    13
90     12
110    12
109     8
120     7
141     7
152     6
181     6
146     6
121     6
156     5
136     5
91      5
183     4
130     4
171     3
70      3
194     3
209     3
164     3
258     2
140     2
134     2
234     2
132     2
131     2
173     1
203     1
161     1
80      1
151     1
103     1
304     1
308     1
326     1
119     1
111     1
79      1
61      1
145     1
Name: engine-size, dtype: int64
fuel-system,mpfi    94
2bbl    66
idi     20
1bbl    11
spdi     9
4bbl     3
mfi      1
spfi     1
Name: fuel-system, dtype: int64
bore,3.62    23
3.19    20
3.15    15
3.03    12
2.97    12
3.46     9
3.31     8
3.78     8
3.43     8
3.27     7
2.91     7
3.39     6
3.54     6
3.05     6
3.58     6
3.7      5
3.01     5
3.35     4
?        4
3.17     3
3.59     3
3.74     3
3.47     2
3.94     2
3.24     2
3.13     2
3.63     2
3.5      2
3.8      2
3.33     2
2.54     1
3.08     1
3.61     1
3.34     1
3.6      1
2.92     1
3.76     1
2.68     1
2.99     1
Name: bore, dtype: int64
stroke,3.4     20
3.23    14
3.15    14
3.03    14
3.39    13
2.64    11
3.29     9
3.35     9
3.46     8
3.11     6
3.27     6
3.41     6
3.07     6
3.58     6
3.19     6
3.5      6
3.64     5
3.52     5
3.86     4
3.54     4
3.47     4
?        4
3.9      3
2.9      3
3.1      2
4.17     2
2.8      2
2.19     2
3.08     2
2.68     2
2.36     1
3.16     1
2.07     1
3.21     1
3.12     1
2.76     1
2.87     1
Name: stroke, dtype: int64
compression-ratio,9.00     46
9.40     26
8.50     14
9.50     13
9.30     11
8.70      9
8.00      8
9.20      8
7.00      7
8.60      5
21.00     5
8.40      5
7.50      5
23.00     5
9.60      5
21.50     4
7.60      4
10.00     3
22.50     3
8.30      3
8.80      3
7.70      2
8.10      2
9.10      1
9.31      1
7.80      1
9.41      1
21.90     1
22.00     1
22.70     1
10.10     1
11.50     1
Name: compression-ratio, dtype: int64
horsepower,68     19
70     11
69     10
116     9
110     8
95      7
88      6
62      6
101     6
160     6
114     6
84      5
97      5
102     5
145     5
82      5
76      5
111     4
92      4
123     4
86      4
90      3
73      3
85      3
207     3
182     3
121     3
152     3
112     2
56      2
161     2
156     2
94      2
52      2
?       2
162     2
155     2
184     2
100     2
176     2
55      1
262     1
134     1
115     1
140     1
48      1
58      1
60      1
78      1
135     1
200     1
64      1
120     1
72      1
154     1
288     1
143     1
142     1
175     1
106     1
Name: horsepower, dtype: int64
peak-rpm,5500    37
4800    36
5000    27
5200    23
5400    13
6000     9
5250     7
4500     7
5800     7
4200     5
4150     5
4750     4
4350     4
5100     3
4250     3
5900     3
4400     3
?        2
6600     2
4650     1
5600     1
5750     1
4900     1
5300     1
Name: peak-rpm, dtype: int64
city-mpg,31    28
19    27
24    22
27    14
17    13
26    12
23    12
21     8
25     8
30     8
38     7
28     7
16     6
37     6
22     4
29     3
15     3
20     3
18     3
14     2
34     1
35     1
32     1
36     1
45     1
13     1
49     1
47     1
33     1
Name: city-mpg, dtype: int64
highway-mpg,25    19
38    17
24    17
30    16
32    16
34    14
37    13
28    13
29    10
33     9
22     8
31     8
23     7
27     5
43     4
42     3
26     3
41     3
19     2
39     2
18     2
16     2
20     2
36     2
47     2
46     2
54     1
17     1
53     1
50     1
Name: highway-mpg, dtype: int64
price,?        4
8921     2
18150    2
8845     2
8495     2
        ..
45400    1
16503    1
5389     1
6189     1
22625    1
Name: price, Length: 187, dtype: int64

In [ ]:
import numpy as np
df.replace('?', np.nan, inplace = True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  164 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       203 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               201 non-null    object
 19  stroke             201 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         203 non-null    object
 22  peak-rpm           203 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              201 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [ ]:
df['price']=pd.to_numeric(df['price'])
df['normalized-losses']=pd.to_numeric(df['normalized-losses'])
df['bore']=pd.to_numeric(df['bore'])
df['stroke']=pd.to_numeric(df['stroke'])
df['horsepower']=pd.to_numeric(df['horsepower'])
df['peak-rpm']=pd.to_numeric(df['peak-rpm'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  164 non-null    float64
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       203 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               201 non-null    float64
 19  stroke             201 non-null    float64
 20  compression-ratio  205 non-null    float64
 21  horsepower         203 non-null    float64
 22  peak-rpm           203 non-null    float64
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              201 non-null    float64
dtypes: float64(11), int64(5), object(10)
memory usage: 41.8+ KB

In [ ]:
# Handling null values
df.isnull().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [ ]:
# Handling missing values in Numeric Column
from sklearn.impute import SimpleImputer
import numpy as np

SI = SimpleImputer(strategy='mean', missing_values=np.nan)
df['normalized-losses'] = SI.fit_transform(df[['normalized-losses']])
df['horsepower'] = SI.fit_transform(df[['horsepower']])
df['bore'] = SI.fit_transform(df[['bore']])
df['stroke'] = SI.fit_transform(df[['stroke']])
df['horsepower'] = SI.fit_transform(df[['horsepower']])
df['peak-rpm'] = SI.fit_transform(df[['peak-rpm']])
df['price'] = SI.fit_transform(df[['price']])

In [ ]:
df.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         2
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [ ]:
# Handling missing values in Categorical column
from sklearn.impute import SimpleImputer
import numpy as np

SI = SimpleImputer(strategy='most_frequent', missing_values=np.nan)
df['num-of-doors'] = SI.fit_transform(df[['num-of-doors']])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    float64
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       205 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               205 non-null    float64
 19  stroke             205 non-null    float64
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    float64
 22  peak-rpm           205 non-null    float64
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    float64
dtypes: float64(11), int64(5), object(10)
memory usage: 41.8+ KB

In [ ]:
df['make'].value_counts()

toyota           32
nissan           18
mazda            17
mitsubishi       13
honda            13
volkswagen       12
subaru           12
peugot           11
volvo            11
dodge             9
mercedes-benz     8
bmw               8
audi              7
plymouth          7
saab              6
porsche           5
isuzu             4
jaguar            3
chevrolet         3
alfa-romero       3
renault           2
mercury           1
Name: make, dtype: int64

In [ ]:
df['fuel-type'].value_counts()

gas       185
diesel     20
Name: fuel-type, dtype: int64

In [ ]:
df['aspiration'].value_counts()

std      168
turbo     37
Name: aspiration, dtype: int64

In [ ]:
df['body-style'].value_counts()

sedan          96
hatchback      70
wagon          25
hardtop         8
convertible     6
Name: body-style, dtype: int64

In [ ]:
df['num-of-cylinders'].value_counts()

four      159
six        24
five       11
eight       5
two         4
three       1
twelve      1
Name: num-of-cylinders, dtype: int64

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
OE=OrdinalEncoder()

In [ ]:
df['make']=OE.fit_transform(df[['make']])
df['fuel-type']=OE.fit_transform(df[['fuel-type']])
df['aspiration']=OE.fit_transform(df[['aspiration']])
df['body-style']=OE.fit_transform(df[['body-style']])
df['num-of-cylinders']=OE.fit_transform(df[['num-of-cylinders']])
df['num-of-doors']=OE.fit_transform(df[['num-of-doors']])
df['drive-wheels']=OE.fit_transform(df[['drive-wheels']])
df['engine-type']=OE.fit_transform(df[['engine-type']])
df['fuel-system']=OE.fit_transform(df[['fuel-system']])
df['engine-location']=OE.fit_transform(df[['engine-location']])
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,122.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,88.6,...,130,5.0,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,122.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,88.6,...,130,5.0,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,122.0,0.0,1.0,0.0,1.0,2.0,2.0,0.0,94.5,...,152,5.0,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,1.0,1.0,0.0,0.0,3.0,1.0,0.0,99.8,...,109,5.0,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,1.0,1.0,0.0,0.0,3.0,0.0,0.0,99.4,...,136,5.0,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,21.0,1.0,0.0,0.0,3.0,2.0,0.0,109.1,...,141,5.0,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,95.0,21.0,1.0,1.0,0.0,3.0,2.0,0.0,109.1,...,141,5.0,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,95.0,21.0,1.0,0.0,0.0,3.0,2.0,0.0,109.1,...,173,5.0,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,95.0,21.0,0.0,1.0,0.0,3.0,2.0,0.0,109.1,...,145,3.0,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,95.0,21.0,1.0,1.0,0.0,3.0,2.0,0.0,109.1,...,141,5.0,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

In [ ]:
X = df.iloc[:, :-1]
Y = df.iloc[:, -1]

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state=2)

In [ ]:
x_train.shape

(143, 25)

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(x_train)
std_xtrain = ss.transform(x_train)
std_xtest = ss.transform(x_test)

In [ ]:
#Lasso
results = []
from sklearn.linear_model import Lasso
model = Lasso(alpha = 0.05, positive = True, max_iter = 100000)
model.fit(std_xtrain, y_train)

from sklearn.metrics import mean_absolute_error
print("With all the 8 features", mean_absolute_error(y_test, model.predict(std_xtest)))
results.append(mean_absolute_error(y_test, model.predict(std_xtest)))

With all the 8 features 2279.777309419742

In [ ]:
from sklearn.feature_selection import RFE
model = Lasso(alpha = 0.05, positive = True, max_iter = 100000)
rfe = RFE(model, n_features_to_select = 15)
rfe.fit(std_xtrain, y_train)

RFE(estimator=Lasso(alpha=0.05, max_iter=100000, positive=True),
    n_features_to_select=15)

In [ ]:
rfe.ranking_

array([ 1,  9,  8,  7,  1,  1,  6,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        3,  4,  5,  1, 10,  1,  2, 11])

In [ ]:
rfe.support_

array([ True, False, False, False,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True, False, False])

In [ ]:
std_xtrain[:,rfe.support_]

array([[ 0.90034639, -0.51525404,  1.1110243 , ..., -0.8372724 ,
        -0.19600834,  0.7165901 ],
       [ 0.90034639, -0.51525404,  1.1110243 , ...,  0.1719456 ,
        -0.41940786,  0.7165901 ],
       [-2.25915138,  1.94079022, -0.90007032, ...,  0.03432496,
        -0.66762955, -0.11399891],
       ...,
       [ 1.69022084, -0.51525404,  1.1110243 , ...,  2.41974931,
        -0.4690522 , -0.84076429],
       [-0.67940249, -0.51525404, -0.90007032, ...,  1.84633   ,
        -0.5435187 ,  0.50894285],
       [ 0.90034639, -0.51525404,  1.1110243 , ...,  0.40131332,
        -0.22083051, -0.73694066]])

In [ ]:
std_xtest[:,rfe.support_]

array([[ 0.11047195, -0.51525404, -0.90007032, -0.5955573 , -0.11909827,
        -0.80392231, -1.33895882, -0.98477371, -1.24596637, -1.1004125 ,
        -0.02645355, -0.10295973, -0.88314594, -0.19600834,  0.7165901 ],
       [ 1.69022084,  1.94079022,  1.1110243 , -0.5955573 , -0.11909827,
        -0.44184077, -0.06993395,  0.14469886, -1.4063022 ,  0.66212855,
        -0.02645355, -0.10295973,  0.63068105, -0.79174039, -0.32164616],
       [-0.67940249, -0.51525404, -0.90007032, -0.5955573 , -0.11909827,
        -0.22788349, -0.05397137, -0.35226907,  0.39747589, -0.51164479,
        -0.02645355, -0.10295973, -0.19504277, -0.41940786,  0.09364835],
       [ 0.90034639, -0.51525404,  1.1110243 ,  1.21645747, -0.11909827,
         0.43044659,  0.21739244, -0.53298468,  0.23714006, -0.33670742,
        -0.02645355, -0.10295973, -0.47028404, -0.34494135,  1.33953186],
       [-1.46927694, -0.51525404, -0.90007032,  1.21645747, -0.11909827,
         0.9406524 ,  1.17514706,  0.55130899,  1.5198267 ,  0.86528163,
        -0.02645355, -0.10295973,  0.28662946, -0.17118617,  0.50894285],
       [ 0.11047195, -0.51525404, -0.90007032, -0.5955573 , -0.11909827,
        -0.90267182, -0.58073641, -0.8040581 ,  0.15697214, -1.18317857,
        -0.02645355, -0.10295973, -0.86020917, -0.29529702, -0.32164616],
       [-0.67940249, -0.51525404, -0.90007032,  1.21645747, -0.11909827,
         1.03940192,  0.07372925,  0.05434106,  0.27722401,  0.18058051,
        -0.02645355, -0.10295973,  0.26369269, -0.5435187 , -0.32164616],
       [-0.67940249, -0.51525404, -0.90007032,  1.21645747, -0.11909827,
         1.03940192,  0.07372925,  0.05434106,  0.27722401,  0.23701192,
        -0.02645355, -0.10295973,  0.12607205,  2.93158491, -1.98282417],
       [ 0.90034639, -0.51525404,  1.1110243 , -0.5955573 , -0.11909827,
        -0.21142524, -0.18965327, -0.21673236,  0.79831546, -0.58876772,
        -0.02645355, -0.10295973, -0.72258854,  3.17980659, -0.73694066],
       [-1.46927694, -0.51525404, -0.90007032, -0.5955573 , -0.11909827,
         0.62794562,  0.12161698,  0.23505667,  0.07680423, -0.30096752,
        -0.02645355, -0.10295973, -0.14916922, -0.36976352, -1.98282417],
       [ 1.69022084,  1.94079022,  1.1110243 , -0.5955573 , -0.11909827,
        -0.44184077, -0.06993395,  0.14469886, -1.4063022 ,  0.44580814,
        -0.02645355, -0.10295973,  0.63068105, -0.79174039, -0.32164616],
       [-0.67940249, -0.51525404, -0.90007032, -0.5955573 , -0.11909827,
        -0.47475727, -0.34927904, -1.07513152,  2.16117001, -0.55302782,
        -0.02645355, -0.10295973, -0.8372724 , -0.29529702, -0.73694066],
       [ 0.90034639, -0.51525404,  1.1110243 , -0.5955573 , -0.11909827,
        -0.21142524, -0.18965327, -0.21673236,  0.79831546, -0.68658216,
        -0.02645355, -0.10295973, -0.44734726, -0.29529702,  0.19747197],
       [-0.67940249, -0.51525404, -0.90007032,  1.21645747, -0.11909827,
         0.43044659,  0.21739244, -0.53298468,  0.23714006,  0.35927998,
        -0.02645355,  1.12397709,  0.81417523, -0.29529702, -1.87900055],
       [ 1.69022084, -0.51525404,  1.1110243 , -0.5955573 , -0.11909827,
         0.0848233 ,  0.99955871,  0.23505667,  0.95865129,  0.25017925,
        -0.02645355, -0.10295973, -0.17210599, -0.22083051,  0.19747197],
       [ 0.11047195, -0.51525404,  1.1110243 , -0.5955573 , -0.11909827,
        -0.67225629, -0.70045574, -0.98477371,  0.31730797, -1.17189229,
        -0.02645355, -0.10295973, -0.72258854, -0.19600834,  0.09364835],
       [ 0.11047195, -0.51525404,  1.1110243 ,  1.21645747, -0.11909827,
        -0.67225629, -0.42909193, -0.89441591, -0.44428722, -0.69598739,
        -0.02645355, -0.10295973, -0.69965176, -0.29529702, -0.73694066],
       [-0.67940249, -0.51525404, -0.90007032, -0.5955573 , -0.11909827,
        -0.34309125, -0.85210022, -0.89441591,  0.31730797, -1.06091052,
        -0.02645355, -0.10295973, -0.8372724 , -0.24565268,  1.75482636],
       [ 1.69022084, -0.51525404,  1.1110243 ,  1.21645747,  8.39642781,
        -1.49516889, -0.41312935, -0.44262688, -0.8451268 ,  0.34235056,
         0.9192607 ,  1.12397709,  1.50227841, -0.17118617,  1.54717911],
       [ 0.11047195, -0.51525404, -0.90007032, -0.5955573 , -0.11909827,
        -0.80392231, -1.33895882, -0.98477371, -1.24596637, -1.14179554,
        -0.02645355, -0.10295973, -0.88314594, -0.19600834,  0.7165901 ],
       [ 0.11047195,  1.94079022,  1.1110243 , -0.5955573 , -0.11909827,
        -0.80392231, -1.33895882, -0.98477371, -1.16579846, -0.83894697,
        -0.02645355, -0.10295973, -0.69965176, -0.64280738,  0.7165901 ],
       [-0.67940249, -0.51525404, -0.90007032, -0.5955573 , -0.11909827,
        -0.67225629, -1.45069686, -1.07513152, -0.68479097, -1.25089626,
        -0.02645355, -0.10295973, -0.88314594, -0.146364  ,  0.50894285],
       [ 0.11047195, -0.51525404, -0.90007032, -0.5955573 , -0.11909827,
         1.18752618,  1.48641731,  2.44882293,  0.79831546,  0.50788269,
        -0.02645355, -1.32989656,  0.1719456 , -0.41940786,  0.7165901 ],
       [-0.67940249, -0.51525404,  1.1110243 ,  1.21645747, -0.11909827,
         0.43044659,  0.21739244, -0.53298468,  0.23714006,  0.25582239,
        -0.02645355,  1.12397709,  0.81417523, -0.29529702, -1.87900055],
       [-0.67940249, -0.51525404, -0.90007032, -0.5955573 , -0.11909827,
         0.03544854,  0.29720532,  0.23505667,  0.71814755, -0.280276  ,
        -0.02645355, -0.10295973, -0.14916922, -0.39458569, -0.73694066],
       [ 0.90034639, -0.51525404,  1.1110243 , -0.5955573 , -0.11909827,
        -1.67620967, -2.63192755, -2.56603533, -0.20378348, -2.04281706,
        -0.97216779,  2.35091391, -1.54831235, -0.17118617, -0.11399891],
       [-0.67940249, -0.51525404, -0.90007032, -0.5955573 , -0.11909827,
        -0.47475727, -0.62064285, -0.7137003 , -0.36411931, -0.87468686,
        -0.02645355, -0.10295973, -0.69965176, -0.29529702, -0.73694066],
       [-1.46927694, -0.51525404, -0.90007032, -0.5955573 , -0.11909827,
         0.62794562,  0.12161698,  0.23505667,  0.4776438 , -0.46649966,
        -0.02645355, -0.10295973, -0.14916922, -0.36976352, -1.98282417],
       [ 0.90034639, -0.51525404,  1.1110243 ,  1.21645747, -0.11909827,
        -0.03038447,  0.16950471, -0.17155346, -0.28395139,  0.75429985,
        -0.02645355, -0.10295973,  0.40131332, -0.22083051, -0.73694066],
       [ 0.11047195, -0.51525404,  1.1110243 ,  1.21645747, -0.11909827,
        -0.67225629, -0.22955972, -0.21673236, -0.52445514,  0.46838071,
         1.86497495,  1.12397709,  0.53893396, -0.29529702, -0.32164616],
       [ 1.69022084, -0.51525404,  1.1110243 ,  1.21645747, -0.11909827,
        -0.54059028, -0.40514806, -0.12637455, -1.64680594, -0.35551789,
         2.8106892 ,  4.80478756, -1.3418814 , -0.19600834,  1.75482636],
       [ 0.90034639, -0.51525404, -0.90007032, -0.5955573 , -0.11909827,
         0.20003106,  0.20142986,  0.09951996,  0.23714006, -0.44580814,
        -0.02645355, -0.10295973, -0.44734726, -0.04707533,  0.7165901 ],
       [ 0.11047195, -0.51525404, -0.90007032, -0.5955573 , -0.11909827,
        -0.80392231, -1.33895882, -0.98477371, -1.24596637, -1.14179554,
        -0.02645355, -0.10295973, -0.88314594, -0.19600834,  0.7165901 ],
       [ 0.11047195, -0.51525404, -0.90007032,  1.21645747, -0.11909827,
         0.80898639,  1.19110963,  0.41577228,  0.79831546,  0.90478361,
        -0.02645355,  1.12397709,  0.81417523, -0.29529702, -1.87900055],
       [ 0.11047195, -0.51525404,  1.1110243 , -0.5955573 , -0.11909827,
        -0.67225629, -1.45069686, -1.07513152, -0.68479097, -1.31673291,
        -0.02645355, -0.10295973, -0.88314594, -0.146364  ,  0.50894285],
       [ 1.69022084, -0.51525404,  1.1110243 ,  1.21645747, -0.11909827,
         0.71023688,  0.75213877,  0.77720351, -0.68479097,  0.7561809 ,
        -2.86359629,  1.12397709,  0.97473264, -0.22083051,  0.09364835],
       [-0.67940249, -0.51525404, -0.90007032,  1.21645747, -0.11909827,
         2.57001935,  1.9812572 ,  1.09345583,  1.19915504,  1.33742443,
        -0.97216779, -0.10295973, -0.19504277, -0.44423003, -0.32164616],
       [ 1.69022084, -0.51525404,  1.1110243 ,  1.21645747, -0.11909827,
         0.71023688,  0.75213877,  0.77720351, -0.68479097,  0.83142278,
        -2.86359629,  1.12397709,  0.97473264, -0.22083051,  0.09364835],
       [-0.67940249,  1.94079022, -0.90007032, -0.5955573 , -0.11909827,
         0.29878057,  0.48875625,  0.41577228,  0.55781172,  0.00940524,
        -0.02645355, -0.10295973, -0.72258854,  3.17980659, -1.35988242],
       [ 0.90034639, -0.51525404, -0.90007032, -0.5955573 , -0.11909827,
        -0.21142524, -0.18965327, -0.21673236,  0.79831546, -0.58312457,
        -0.02645355, -0.10295973, -0.72258854,  3.17980659, -0.73694066],
       [-0.67940249, -0.51525404, -0.90007032,  1.21645747, -0.11909827,
         1.53314948,  1.00754   ,  1.09345583,  1.19915504,  0.94240455,
        -0.97216779, -0.10295973, -0.19504277, -0.44423003, -0.32164616],
       [-1.46927694, -0.51525404, -0.90007032,  1.21645747, -0.11909827,
         2.80043488,  2.27656487,  2.58435964,  1.11898712,  2.19330082,
         1.86497495, -2.55683338,  2.41974931, -0.4690522 , -0.84076429],
       [-0.67940249,  1.94079022,  1.1110243 , -2.40757208, -0.11909827,
         0.15065631,  0.32913048,  0.86756132, -0.68479097,  0.90102152,
        -0.02645355, -1.32989656,  0.05726173, -0.79174039,  0.7165901 ],
       [ 0.11047195, -0.51525404,  1.1110243 , -0.5955573 , -0.11909827,
        -0.80392231, -1.33895882, -0.98477371, -1.16579846, -1.23396684,
        -0.02645355, -0.10295973, -0.88314594, -0.19600834,  0.7165901 ],
       [-1.46927694,  1.94079022, -0.90007032, -0.5955573 , -0.11909827,
         0.62794562,  0.12161698,  0.23505667,  0.4776438 , -0.17681842,
        -0.02645355, -0.10295973, -0.42441049,  3.05569575, -1.35988242],
       [-0.67940249, -0.51525404, -0.90007032, -0.5955573 , -0.11909827,
        -0.26079999, -0.04599008, -0.26191126, -0.28395139, -0.53421735,
         0.9192607 , -0.10295973, -0.47028404, -0.29529702, -0.73694066],
       [ 0.11047195, -0.51525404, -0.90007032, -0.5955573 , -0.11909827,
        -0.90267182, -0.58073641, -0.8040581 ,  0.15697214, -1.17377334,
        -0.02645355, -0.10295973, -0.86020917, -0.29529702, -0.32164616],
       [ 0.90034639, -0.51525404,  1.1110243 , -2.40757208, -0.11909827,
        -0.86975532, -1.33895882, -0.98477371,  0.79831546, -0.6282697 ,
         0.9192607 , -0.10295973, -0.47028404, -0.36976352, -1.56752967],
       [ 0.11047195, -0.51525404, -0.90007032, -0.5955573 , -0.11909827,
        -0.80392231, -0.54082997, -0.98477371, -1.16579846, -0.72044101,
        -0.02645355, -0.10295973, -0.69965176, -0.19600834,  0.7165901 ],
       [ 0.90034639, -0.51525404,  1.1110243 ,  1.21645747, -0.11909827,
        -0.03038447,  0.16950471, -0.17155346, -0.68479097, -0.04326408,
        -0.02645355, -0.10295973,  0.40131332, -0.22083051, -0.73694066],
       [-0.67940249, -0.51525404, -0.90007032,  1.21645747, -0.11909827,
         2.37252033,  2.03712621,  1.63560267, -0.36411931,  2.80652214,
        -2.86359629,  1.12397709,  2.97023185, -0.51869653, -0.84076429],
       [ 0.11047195, -0.51525404,  1.1110243 , -0.5955573 , -0.11909827,
        -0.34309125, -0.39716678,  0.00916216, -1.08563054, -0.52857421,
        -0.02645355, -0.10295973, -0.42441049, -0.27047485,  0.7165901 ],
       [-0.67940249, -0.51525404, -0.90007032, -0.5955573 , -0.11909827,
        -0.22788349, -0.16570941, -0.26191126, -0.48437118, -0.80696917,
         0.9192607 , -0.10295973, -0.47028404, -0.17118617, -0.73694066],
       [-0.67940249, -0.51525404, -0.90007032, -0.5955573 , -0.11909827,
        -0.22788349, -0.16570941, -0.26191126, -0.48437118, -0.72232205,
         0.9192607 , -0.10295973, -0.47028404, -0.17118617, -1.56752967],
       [-1.46927694,  1.94079022, -0.90007032,  1.21645747, -0.11909827,
         1.7306485 ,  1.17514706,  1.31935035,  0.71814755,  0.91795094,
        -0.02645355, -0.10295973,  0.28662946, -0.17118617,  0.50894285],
       [-0.67940249, -0.51525404, -0.90007032,  1.21645747, -0.11909827,
         2.57001935,  1.9812572 ,  1.09345583,  2.00083418,  1.23396684,
        -0.97216779, -0.10295973, -0.19504277, -0.44423003, -0.32164616],
       [-1.46927694, -0.51525404, -0.90007032,  1.21645747, -0.11909827,
         0.97356891,  1.09533417,  0.23505667,  0.15697214,  1.08536413,
        -2.86359629,  1.12397709,  0.74536491, -0.24565268,  0.09364835],
       [ 0.11047195, -0.51525404,  1.1110243 ,  1.21645747, -0.11909827,
         0.10128155,  0.35307434,  0.86756132, -1.60672199,  1.06279156,
         1.86497495,  1.12397709,  1.20410036, -0.29529702,  0.09364835],
       [-1.46927694, -0.51525404, -0.90007032, -0.5955573 , -0.11909827,
         0.77606988,  0.04180409, -0.62334249,  2.44175772, -0.07336083,
        -0.02645355, -0.10295973, -0.14916922, -0.41940786, -0.32164616],
       [-0.67940249, -0.51525404, -0.90007032, -0.5955573 , -0.11909827,
        -0.34309125,  0.1056544 , -0.35226907,  0.15697214, -0.20503412,
        -0.02645355, -0.10295973, -0.42441049, -0.29529702,  1.33953186],
       [ 0.11047195, -0.51525404,  1.1110243 , -0.5955573 , -0.11909827,
        -0.67225629, -0.70045574, -0.98477371,  0.31730797, -1.2885172 ,
        -0.02645355, -0.10295973, -0.72258854, -0.19600834,  0.09364835],
       [-0.67940249, -0.51525404, -0.90007032, -2.40757208, -0.11909827,
        -0.26079999, -0.16570941, -0.26191126,  0.23714006, -0.35551789,
         0.9192607 , -0.10295973, -0.47028404, -0.29529702, -0.73694066]])

In [ ]:
#With top 15 features
model.fit(std_xtrain[:,rfe.support_], y_train)
mean_absolute_error(y_test, model.predict(std_xtest[:,rfe.support_]))

2278.5602174488945

In [ ]:
model = Lasso(alpha = 0.05, positive = True, max_iter = 100000)

for num_selected_features in list(range(15,0,-1)):
    rfe = RFE(model, n_features_to_select = num_selected_features)
    rfe.fit(std_xtrain, y_train)
    model.fit(std_xtrain[:,rfe.support_], y_train)
    results.append(mean_absolute_error(y_test, model.predict(std_xtest[:,rfe.support_])))

In [ ]:
for j in range(len(results)):
    if(min(results) == results[j]):
        ind = j

#Best number of features
len(results) - ind

11

In [ ]:
rfe = RFE(model, n_features_to_select = 15)
rfe.fit(std_xtrain, y_train)
rfe.ranking_

array([ 1,  9,  8,  7,  1,  1,  6,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        3,  4,  5,  1, 10,  1,  2, 11])

In [ ]:
selected_features = rfe.support_

In [ ]:
selected_features

array([ True, False, False, False,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True, False, False])

In [ ]:
import numpy as np

# Assuming 'rfe' is the RFE object and 'std_xtrain' is a NumPy array
selected_features = rfe.support_

# Get the top 15 selected feature indices
top_15_indices = np.where(selected_features)[0][:15]

# Define a list of feature names
feature_names = [
    'symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg']

# Print the top 15 features
for index in top_15_indices:
    print(feature_names[index])

symboling
aspiration
num-of-doors
drive-wheels
engine-location
wheel-base
length
width
height
curb-weight
engine-type
num-of-cylinders
engine-size
compression-ratio
peak-rpm

In [ ]:
results

[2279.777309419742,
 2278.5602174488945,
 2279.019264764603,
 2276.4515878766297,
 2253.0245359808123,
 2249.645525737947,
 2267.8331546984487,
 2348.2759873849404,
 2349.307210625733,
 2391.459812029817,
 2369.9560747196674,
 2377.078804205228,
 2437.8043547574084,
 2329.9008771551034,
 2528.70558246239,
 2691.2108643464094]

In [ ]:
min(results)

2249.645525737947

In [ ]:
import numpy as np

# Assuming 'rfe' is the RFE object and 'std_xtrain' is a NumPy array
selected_features = rfe.support_

# Set the cutoff value for selecting features
cutoff_value = 0.9  # Adjust this value as needed

# Calculate the number of features to be selected based on the cutoff value
num_selected_features = int(np.sum(selected_features) * cutoff_value)

# Get the top selected feature indices
top_indices = np.argsort(rfe.ranking_)[:num_selected_features]

# Define a list of feature names corresponding to your dataset
feature_names = [
    'symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg']


# Print the selected features
for index in top_indices:
    print(feature_names[index])

symboling
peak-rpm
compression-ratio
engine-size
num-of-cylinders
engine-type
curb-weight
width
length
height
engine-location
drive-wheels
num-of-doors